# Generated by Django 5.1.5 on 2025-01-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('morador', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('data_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('convidado', models.CharField(max_length=255)),
            ],
        ),
    ]
